onlyBuiltDependencies:
  - '@parcel/watcher'
  - electron-winstaller
  - esbuild

overrides:
  '@types/node': '24.1.0'

minimumReleaseAgeExclude:
  - knip@6.40.0
  - nanoid@6.0.2
  - nuxt@4.1.3
  - '@nuxt/kit@4.1.3'
  - '@nuxt/schema@4.1.3'
  - '@nuxt/nitro-server@4.1.3'
  - '@nuxt/vite-builder@4.1.3'
  - '@nuxt/vite-server@4.1.3'
  - electron@44.6.0

allowBuilds:
  '@parcel/watcher': set this to true or false
  electron-winstaller: set this to true or false
  esbuild: set this to true or false
