export { useScriptTriggerConsent, useScriptEventPage, useScriptTriggerElement, useScript, useScriptGoogleAnalytics, useScriptPlausibleAnalytics, useScriptCrisp, useScriptClarity, useScriptCloudflareWebAnalytics, useScriptVercelAnalytics, useScriptPostHog, useScriptFathomAnalytics, useScriptMatomoAnalytics, useScriptMixpanelAnalytics, useScriptBingUet, useScriptGoogleTagManager, useScriptGoogleAdsense, useScriptGoogleRecaptcha, useScriptGoogleSignIn, useScriptSegment, useScriptMetaPixel, useScriptXPixel, useScriptTikTokPixel, useScriptIntercom, useScriptHotjar, useScriptStripe, useScriptLemonSqueezy, useScriptVimeoPlayer, useScriptYouTubePlayer, useScriptGoogleMaps, useScriptNpm, useScriptUmamiAnalytics, useScriptSnapchatPixel, useScriptRybbitAnalytics, useScriptDatabuddyAnalytics, useScriptRedditPixel, useScriptPayPal, useScriptGravatar, useScriptAhrefsAnalytics, useScriptLinkedInInsight, useScriptCalendly, useScriptUsercentrics } from '#app/composables/script-stubs';
export { isVue2, isVue3 } from 'vue-demi';
export { defineNuxtLink } from '#app/components/nuxt-link';
export { useNuxtApp, tryUseNuxtApp, defineNuxtPlugin, definePayloadPlugin, useRuntimeConfig, defineAppConfig } from '#app/nuxt';
export { useAppConfig, updateAppConfig } from '#app/config';
export { defineNuxtComponent } from '#app/composables/component';
export { useAsyncData, useLazyAsyncData, useNuxtData, refreshNuxtData, clearNuxtData, createUseAsyncData } from '#app/composables/asyncData';
export { useHydration } from '#app/composables/hydrate';
export { callOnce } from '#app/composables/once';
export { useState, clearNuxtState } from '#app/composables/state';
export { clearError, createError, isNuxtError, showError, useError } from '#app/composables/error';
export { useFetch, useLazyFetch, createUseFetch } from '#app/composables/fetch';
export { useCookie, refreshCookie } from '#app/composables/cookie';
export { onPrehydrate, prerenderRoutes, useRequestHeader, useRequestHeaders, useResponseHeader, useRequestEvent, useRequestFetch, setResponseStatus } from '#app/composables/ssr';
export { onNuxtReady } from '#app/composables/ready';
export { preloadComponents, prefetchComponents, preloadRouteComponents } from '#app/composables/preload';
export { abortNavigation, addRouteMiddleware, defineNuxtRouteMiddleware, setPageLayout, navigateTo, useRoute, useRouter } from '#app/composables/router';
export { isPrerendered, loadPayload, preloadPayload, definePayloadReducer, definePayloadReviver } from '#app/composables/payload';
export { useLoadingIndicator } from '#app/composables/loading-indicator';
export { getAppManifest, getRouteRules } from '#app/composables/manifest';
export { reloadNuxtApp } from '#app/composables/chunk';
export { useRequestURL } from '#app/composables/url';
export { usePreviewMode } from '#app/composables/preview';
export { useRouteAnnouncer } from '#app/composables/route-announcer';
export { useAnnouncer } from '#app/composables/announcer';
export { useRuntimeHook } from '#app/composables/runtime-hook';
export { useHead, useHeadSafe, useServerHeadSafe, useServerHead, useSeoMeta, useServerSeoMeta, injectHead } from '#app/composables/head';
export { onBeforeRouteLeave, onBeforeRouteUpdate, useLink } from 'vue-router';
export { withCtx, withDirectives, withKeys, withMemo, withModifiers, withScopeId, onActivated, onBeforeMount, onBeforeUnmount, onBeforeUpdate, onDeactivated, onErrorCaptured, onMounted, onRenderTracked, onRenderTriggered, onServerPrefetch, onUnmounted, onUpdated, computed, customRef, isProxy, isReactive, isReadonly, isRef, markRaw, proxyRefs, reactive, readonly, ref, shallowReactive, shallowReadonly, shallowRef, toRaw, toRef, toRefs, triggerRef, unref, watch, watchEffect, watchPostEffect, watchSyncEffect, onWatcherCleanup, isShallow, effect, effectScope, getCurrentScope, onScopeDispose, defineComponent, defineAsyncComponent, resolveComponent, getCurrentInstance, h, inject, hasInjectionContext, nextTick, provide, toValue, useModel, useAttrs, useCssModule, useSlots, useTransitionState, useId, useTemplateRef, useShadowRoot, useCssVars, Component, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue';
export { requestIdleCallback, cancelIdleCallback } from '#app/compat/idle-callback';
export { setInterval } from '#app/compat/interval';
export { definePageMeta, PageMeta } from '#app/composables/pages';
export { defineLazyHydrationComponent } from '#app/composables/lazy-hydration';
export { useAudioEngine } from '../app/composables/useAudioEngine';
export { useCompanions } from '../app/composables/useCompanions';
export { useConfig, IUiConfig, ILabelConfig, ICategory, IRelation, IColumnConfig, IActionButtonConfig, ISimulatorConfig, ISederConfig, IConfig } from '../app/composables/useConfig';
export { useCustomAssets } from '../app/composables/useCustomAssets';
export { useDatabase } from '../app/composables/useDatabase';
export { useDatabasePage } from '../app/composables/useDatabasePage';
export { useEditorLogic } from '../app/composables/useEditorLogic';
export { useFamily } from '../app/composables/useFamily';
export { useFamilyActions } from '../app/composables/useFamilyActions';
export { useHistory } from '../app/composables/useHistory';
export { useJournal } from '../app/composables/useJournal';
export { useJournalPage } from '../app/composables/useJournalPage';
export { usePatronymic } from '../app/composables/usePatronymic';
export { usePersonGenerator, IPersonAppearance } from '../app/composables/usePersonGenerator';
export { usePhysics } from '../app/composables/usePhysics';
export { useScenarioRunner } from '../app/composables/useScenarioRunner';
export { useSceneBuilder } from '../app/composables/useSceneBuilder';
export { useScriptInterpreter } from '../app/composables/useScriptInterpreter';
export { useSeeder } from '../app/composables/useSeeder';
export { useShift } from '../app/composables/useShift';
export { Direction, TravelMode, SubState, AgentState, SceneElement, AiAgent, ScriptCommand, TrafficConfig, SimulatorConfig } from '../app/composables/useSimulator';
export { useSimulatorData } from '../app/composables/useSimulatorData';
export { useSimulatorDatabase } from '../app/composables/useSimulatorDatabase';
export { useSimulatorIntegration } from '../app/composables/useSimulatorIntegration';
export { useSimulatorScaling } from '../app/composables/useSimulatorScaling';
export { useSimulatorScene } from '../app/composables/useSimulatorScene';
export { useTextUtils } from '../app/composables/useTextUtils';
export { useTheme } from '../app/composables/useTheme';
export { useVirtualList } from '../app/composables/useVirtualList';
export { isPointInPolygon } from '../app/utils/geometry';
export { renderPersonSvg, PersonAppearance } from '../app/utils/personSvgRenderer';
export { personToSvg } from '../app/utils/personToSvg';
export { PERSON_STOP_OFFSET, CAR_STOP_OFFSET, PERSON_VERTICAL_OFFSET, EXIT_HORIZONTAL_DISTANCE, EXIT_VERTICAL_DISTANCE, DESPAWN_MARGIN, USE_MANUAL_COORDS, MANUAL_Y_PERSON, MANUAL_X_PERSON, MANUAL_Y_CAR, MANUAL_X_CAR, MANUAL_PERSON_GATE_ID, MANUAL_CAR_GATE_ID, GATES_LIST, PERSON_WIDTH, PERSON_HEIGHT, CAR_WIDTH, CAR_HEIGHT, CAR_COLORS, SPRITE_ORIENTATION_OFFSET, ACCEL, DECEL, REACTION_TIME, MIN_BUFFER, MAX_LOOKAHEAD, DEADLOCK_TIME, REVERSE_TIME, REVERSE_SPEED, ARRIVE_THRESHOLD, TRAFFIC_CONFIG } from '../app/utils/simulatorConstants';
export { dot, cross, normalizeAngle } from '../app/utils/simulatorMath';
export { getCarSvg, getRandomCarColor, generateRealPersonSvg } from '../app/utils/simulatorSvg';
export { usePWA, useTransparentPwaIcon, useMaskablePwaIcon, useFaviconPwaIcon, useApplePwaIcon, useAppleSplashScreenPwaIcon } from '../node_modules/@vite-pwa/nuxt/dist/runtime/composables/index';
export { useGSAP } from '../node_modules/v-gsap-nuxt/dist/runtime/plugin';
export { useNuxtDevTools } from '../node_modules/@nuxt/devtools/dist/runtime/use-nuxt-devtools';